### ISSUE TITLE
Support Thunderstorm, Next-Week, and Status Properties in Icelandic

### ISSUE THREAD

**Issue by ironwallaby** [darkskyapp/translations#104]
In the near future, the API will begin generating the following new properties:

*   `possible-thunderstorm`
*   `thunderstorm`
*   `next-sunday`
*   `next-monday`
*   `next-tuesday`
*   `next-wednesday`
*   `next-thursday`
*   `next-friday`
*   `next-saturday`
*   `next-hour-forecast-status`
*    `unavailable`
*    `temporarily-unavailable`
*    `partially-unavailable`
*    `station-offline`
*    `station-incomplete`

Add support for these properties to Icelandic. (Information is available in the README, and examples are visible in `/lib/lang/en.js` and `/test_cases/en.js`.)

**Comment by ironwallaby** [comment]
Tagging @valgeirb. Please take a look if you get a chance!

**Comment by valgeirb** [comment]
Will try to find time for this.

**Comment by nonrenewable** [comment]
Edit: Added new status message properties as well.
