### ISSUE TITLE
Support Thunderstorm, Next-Week, and Status Properties in Tetum

### ISSUE THREAD

**Issue by ironwallaby** [darkskyapp/translations#115]
In the near future, the API will begin generating the following new properties:

*   `possible-thunderstorm`
*   `thunderstorm`
*   `next-sunday`
*   `next-monday`
*   `next-tuesday`
*   `next-wednesday`
*   `next-thursday`
*   `next-friday`
*   `next-saturday`
*   `next-hour-forecast-status`
*    `unavailable`
*    `temporarily-unavailable`
*    `partially-unavailable`
*    `station-offline`
*    `station-incomplete`

Add support for these properties to Tetum. (Information is available in the README, and examples are visible in `/lib/lang/en.js` and `/test_cases/en.js`.)

**Comment by nonrenewable** [comment]
Tagging @macdhuibh if you have an opportunity to take a look!
