### ISSUE TITLE
Make weekly temperature summaries more precise

### ISSUE THREAD

**Issue by ironwallaby** [darkskyapp/translations#158]
A Dark Sky API customer noted that this summary is poor: "Bruine demain, avec des températures atteignant 24°C jeudi." (Translation: "Drizzle tomorrow, with temperatures bottoming out at 24°C on Thursday.")

They recommend using this instead: "Bruine demain, avec des températures _maximales_ atteignant 24°C jeudi." (Translation: "Drizzle tomorrow, with high temperatures bottoming out at 24°C on Thursday.")

This could be fixed across the board (e.g. in all languages) to make the summaries more precise.

**Comment by TheoL** [comment]
Are you planning to make this change in English? What about "temperatures-falling"?

**Comment by steronydh** [comment]
My school French is now very rusty but Google translates "Bruine demain, avec des températures maximales atteignant 24°C jeudi." as "Drizzle tomorrow, with maximum temperatures up to 24 ° C on Thursday". 

I would parse "bottoming out" as meaning "reaching a minimum" not "reaching a maximum". This might be a UK/USA difference, I'm not sure.

For clarity I think the English should avoid the phrase "bottoming out" if there's a risk of misinterpretation.

**Comment by ironwallaby** [comment]
These changes (in English and French) have been incorporated into 2.0.0. Other languages can be updated opportunistically!

**Comment by TheoL** [comment]
Are these changes non in production yet? I still get results such as "... with temperatures bottoming out ..." instead of "... with high temperatures bottoming out ..."

**Comment by ironwallaby** [comment]
Not yet, no. We started rolling this update (along with a number of others) into staging yesterday; if things go well it'll land in production today or tomorrow. (If not, early next week probably :) )

Sorry for the delay on getting this live!
