### ISSUE TITLE
Add "chance of X" to summaries?

### ISSUE THREAD

**Issue by ironwallaby** [darkskyapp/translations#163]
It is often the case that there is a lot of precipitation predicted, but only with a small chance of occurring. (Such as "20% chance of snow (11-17 in.) overnight".) It would be excellent to support this case in the translations... but how do languages other than English handle such things? How generic should we make this?

**Comment by steronydh** [comment]
The sentence structure for Cornish can be the same, so no problem.

**Comment by srmihnev** [comment]
Assuming the sentence is "[X]% chance of [condition] [when]", I suppose it can be translated in many languages.

**Comment by rereradu** [comment]
Looong time since this was first brought up, but I think Romanian translations should be ok with this as well.
