### ISSUE TITLE
Changing the language should also change the time representation

### ISSUE THREAD

**Issue by CreamyCookie** [darkskyapp/translations#186]
In German AM / PM isn't used. Instead we use the normal [24-hour clock](https://en.wikipedia.org/wiki/24-hour_clock). (21:00 instead of 9:00 p.m.)

**Comment by ironwallaby** [comment]
Hi! Can you clarify? I don't see any references to times in the summaries themselves---we prefer saying things like "morning" or "afternoon" instead of saying "10:00 AM" or anything like that.

**Comment by CreamyCookie** [comment]
Huh.. maybe I incorrectly reported this here. This is about the website darksky.net. For example, for [Berlin](https://darksky.net/forecast/52.517,13.3889/si12/de), there are a lot of AM and PM:  
![screenshot](https://user-images.githubusercontent.com/3063858/46721020-59384c80-cc72-11e8-827f-d98ac26c3b61.png)

**Comment by ironwallaby** [comment]
Ah! The website is unrelated to this project. I'll copy your issue there for the relevant team to look into. Thanks!
