### ISSUE TITLE
Embeded widget GraphBar not fully translated

### ISSUE THREAD

**Issue by manytwo** [darkskyapp/translations#192]
Some texts in embed widget GraphBar (https://darksky.net/widgets/graphbar) is not translated.

Summary is translated but not text inside the central bar (overcast, Rain, Mostly cloudy,...).

**Comment by ironwallaby** [comment]
That text is the responsibility of a separate (internal) project, and I have copied your ticket to it.

Thank you!

**Comment by manytwo** [comment]
Ok thanks! 
Some texts have been hardcoded into JS I presume. For information, same problem on an other widget : 
![darkskywidget](https://user-images.githubusercontent.com/2377564/49017982-72e21480-f18a-11e8-87fe-92070535e67c.PNG)
default embeded (https://darksky.net/widgets/default).  Hope this helps!

**Comment by ironwallaby** [comment]
Yup, that's exactly right—these strings are hardcoded into the project, and since it's a smaller project it hasn't received the same level of attention as this one. (Sorry!) 

I've added that extra information to it as well. Thanks again!
