### ISSUE TITLE
Malayalam and Urdu translation are not supported

### ISSUE THREAD

**Issue by rizkiaditya24** [darkskyapp/translations#214]
malayalam and urdu have been merged into master, but still can't use both languages in the API, got this error:

```
GET https://api.darksky.net/forecast/<API_KEY>/52.52394974,13.0323323?lang=ur

{
    "code": 400,
    "error": "An invalid lang parameter was provided."
}
```

**Comment by ironwallaby** [comment]
Correct: that version is not yet live on the API. (Sorry! The latest update with translations is [this one](https://status.darksky.net/2019/02/13/model-updates.html).)

We'll try to get the latest version live soon.
