### ISSUE TITLE
Error in Czech translation 

### ISSUE THREAD

**Issue by rudahes** [darkskyapp/translations#229]
"cloudy"
Wrong translation: "zataženo" 
The right translation is "oblačno"

**Comment by ironwallaby** [comment]
We have three levels of "cloudy":

*   "partly cloudy" -> "částečně zataženo"
*   "mostly cloudy" -> "převážně zataženo"
*   "overcast" -> "zataženo"

Should "zataženo" be replaced with "oblačno" in all three cases?

**Comment by rudahes** [comment]
Zataženo should be replaced only in first two cases :

"partly cloudy" -> "částečně oblačno"
"mostly cloudy" -> "převážně oblačno"
"overcast" -> "zataženo"

Dne po 12. srp 2019 19:12 uživatel Jay LaPorte <notifications@github.com>
napsal:

**Comment by ironwallaby** [comment]
OK, thanks! A couple last things to check: are these translations grammatically reasonable?

```
Mostly cloudy throughout the day. -> Během dne převážně oblačno.
Partly cloudy starting in the afternoon, continuing until evening. -> Od odpoledne částečně oblačno a přetrvá až do večera.
```

**Comment by rudahes** [comment]
Yes these translations are correct. :)

Dne út 13. srp 2019 16:30 uživatel Jay LaPorte <notifications@github.com>
napsal:

**Comment by ironwallaby** [comment]
OK! This is fixed and will go live on our next API deploy, whenever that is. Thanks!
