### ISSUE TITLE
Scottish Gaelic: An invalid lang parameter was provided

### ISSUE THREAD

**Issue by MacMhicheil** [darkskyapp/translations#238]
I'm getting the below error when trying to use the Scottish Gaelic translation.

{"code":400,"error":"An invalid lang parameter was provided."}

I'm using a URL in the following format: https://api.darksky.net/forecast/[key]/[latitude],[longitude]?lang=gd&units=si

Changing the language from gd to en, for example, gives the correct result. Do I need to do anything else to be able to use the Gaelic translation or am I just been too hasty in trying to use it when it was only merged to the master branch yesterday evening?

**Comment by ironwallaby** [comment]
Just too hasty: we have not yet done a production deploy to include the language. You can keep an eye on http://status.darksky.net/ , which will report when it's live! (I warn you, it'll probably be a week!)

**Comment by ironwallaby** [comment]
I lied, we'll have this live before the end of the day, US Eastern Time.

**Comment by MacMhicheil** [comment]
OK, thanks for letting me know.
