### ISSUE TITLE
Support Status Properties in Scottish Gaelic

### ISSUE THREAD

**Issue by nonrenewable** [darkskyapp/translations#254]
In the near future, the API will begin using the following new properties:

*   `next-hour-forecast-status`
*    `unavailable`
*    `temporarily-unavailable`
*    `partially-unavailable`
*    `station-offline`
*    `station-incomplete`

Add support for these properties to Scottish Gaelic. (Information is available in the [README]( https://github.com/darkskyapp/translations/#status-information), and examples are visible in `/lib/lang/en.js` and `/test_cases/en.js`.)

Tagging @MacMhicheil  if you have an opportunity to take a look!

**Comment by MacMhicheil** [comment]
Added support for these in #294
