### ISSUE TITLE
Support Status Properties in Dutch

### ISSUE THREAD

**Issue by nonrenewable** [darkskyapp/translations#268]
In the near future, the API will begin using the following new properties:

*   `next-hour-forecast-status`
*    `unavailable`
*    `temporarily-unavailable`
*    `partially-unavailable`
*    `station-offline`
*    `station-incomplete`

Add support for these properties to Dutch. (Information is available in the [README]( https://github.com/darkskyapp/translations/#status-information), and examples are visible in `/lib/lang/en.js` and `/test_cases/en.js`.)

Tagging @realjax, @cygnus6, and @michaelarnauts if you have an opportunity to take a look!

**Comment by realjax** [comment]
Hi,
On it, but It is not clear to me what this would be
"next-hour-forecast-status": "next hour forecasts are $1 due to $2",

What do the variables represent here?
The docs say 'we have information to convey about our hyperlocal next-hour forecasts' which also sounds a bit cryptic to me..

**Comment by ironwallaby** [comment]
Sorry for being cryptic, we'll see what we can do about the docs. In the meantime, perhaps the best example of how these are used are in the English test cases:

https://github.com/darkskyapp/translations/blob/master/test_cases/en.json#L265-L272
```
  "Next hour forecasts are temporarily unavailable due to all nearby radar stations being offline.":
    ["sentence", ["next-hour-forecast-status", "temporarily-unavailable", "station-offline"]],

  "Next hour forecasts are partially unavailable due to gaps in coverage from nearby radar stations.":
    ["sentence", ["next-hour-forecast-status", "partially-unavailable", "station-incomplete"]],

  "Next hour forecasts are unavailable due to all nearby radar stations being offline.":
    ["sentence", ["next-hour-forecast-status", "unavailable", "station-offline"]]
```

**Comment by realjax** [comment]
Ok, thanks for that,clear now :) . I have translated the missing pieces and will create a PR.
