### ISSUE TITLE
Support Thunderstorm, Next-Week, and Status Properties in Arabic

### ISSUE THREAD

**Issue by ironwallaby** [darkskyapp/translations#88]
In the near future, the API will begin generating the following new properties:

*   `possible-thunderstorm`
*   `thunderstorm`
*   `next-sunday`
*   `next-monday`
*   `next-tuesday`
*   `next-wednesday`
*   `next-thursday`
*   `next-friday`
*   `next-saturday`
*   `next-hour-forecast-status`
*    `unavailable`
*    `temporarily-unavailable`
*    `partially-unavailable`
*    `station-offline`
*    `station-incomplete`

Add support for these properties to Arabic. (Information is available in the README, and examples are visible in `/lib/lang/en.js` and `/test_cases/en.js`.)

**Comment by ironwallaby** [comment]
Tagging @FajrAljunaid. Please take a look if you have a chance!

**Comment by FajrAljunaid** [comment]
OK, will do as soon as I get a chance!

**Comment by nonrenewable** [comment]
Edit: Added new `STATUS` messages to this ticket as well

**Comment by nonrenewable** [comment]
Just looked a little closer, looks like this ticket was resolved previously so will simply close and open a new one for status messages alone to make clearer
